import {StyleSheet} from 'react-native'
import { color } from 'react-native-reanimated';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      
      alignItems: 'center',
      justifyContent: 'center',
    },
    Przepiscontainer:{
      flex: 1,
      backgroundColor: '#888888',
    },
    bgimage: {
      alignItems: 'center',
      justifyContent: 'center',
      height: '100%',
      width: '100%',
    },
    containerPic: {
      backgroundColor: '#DDDDDD',
      flexDirection: 'row',
    },
    button: {
      justifyContent: 'center',
      paddingVertical: 20,
      paddingHorizontal: 32,
      borderRadius: 4,
      width: 200,
      elevation: 3,
      backgroundColor: '#AAAAAA',
      marginVertical: 20,
      alignItems: 'center',
      borderWidth: 1,
      color: '#000000',
    },
    przycisk: {
      justifyContent: 'center',
      paddingVertical: 20,
      paddingHorizontal: 32,
      borderRadius: 4,
      width: 200,
      elevation: 3,
      backgroundColor: '#AAAAAA',
      marginVertical: 20,
      alignItems: 'center',
      borderWidth: 1,
      color: '#000000',
    },
    text: {
      fontSize: 16,
      lineHeight: 21,
      fontWeight: 'bold',
      letterSpacing: 0.25,
      color: '#000000',
    },
    text1: {
      fontSize: 16,
      lineHeight: 21,
      letterSpacing: 0.25,
      color: 'white',
    },
    recipebutton: {
      borderWidth: 1,
      padding: 10,
      width: '100%',
      backgroundColor: 'rgba(0,0,0,0.5)',
      margin: 2,
    },
    dataText: {
      fontSize: 16,
      lineHeight: 51,
      fontWeight: 'bold',
      letterSpacing: 0.25,
      color: 'black',
      backgroundColor: '#204075',
      borderWidth:2,
      borderRadius: 6,
      textAlign: 'center'
    },
    title: {
      marginTop: 10,
      fontSize: 30,
      fontWeight: 'bold',
      color: 'white',
    },
    authors: {
      fontSize: 20,
      bottom: 0,
      fontWeight: 'bold',
      justifyContent: 'center',
      color: 'white',
    },
    separator: {
      marginVertical: 30,
      height: 1,
      width: '80%',
    },
    input: {
      borderWidth:2,
      borderColor: '#AAAAAA',
      margin: 20,
      width:280,
      padding: 15,
      backgroundColor: 'rgba(1,1,1,0.8)',
      color: 'white',
    },
    camera: {
      flex: 1,
      borderRadius:20,
    },
    buttonContainer: {
      flex:1,
      width:'15%',
      height:'8%',
    },
    takebutton: {
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth:1,
      flex:1,
      position:"absolute",
      top:'91%',
      left:'42%',
      borderRadius:50,
      backgroundColor:'#3040B388',
      borderColor:"white",
    },
    flipbutton: {
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth:1,
      flex:1,
      position:"absolute",
      bottom:'91%',
      left:'42%',
      borderRadius:50,
      backgroundColor:'#3040B388',
      borderColor:"white",
    },
    camcontainer: {
      flex: 1,
      paddingTop:'10%',
      paddingBottom:'10%',
      backgroundColor:'black',
    },
    foodimages: {
      width:  300,
      height: 300,
      margin: 10,
    }
  });

export default styles